In [2]:
import torch

print(torch.cuda.is_available())

True


### Alphapose command

* Input dir: Run AlphaPose for all images in a folder with:
python scripts/demo_inference.py --cfg <cfg_file> --checkpoint <trained_model> --indir <img_directory> --outdir <output_directory>

* Choose a different detector: Default detector is yolov3-spp, it works pretty well, if you want to use yolox series, remember to download their weight according to our installation readme. Options include [yolox-x|yolox-l|yolox-m|yolox-s|yolox-darknet]:
python scripts/demo_inference.py --detector yolox-x --cfg <cfg_file> --checkpoint <trained_model> --indir <img_directory> --outdir <output_directory>

* Video: Run AlphaPose for a video and save the rendered video with:
python scripts/demo_inference.py --cfg configs/halpe_26/resnet/256x192_res50_lr1e-3_2x.yaml --checkpoint pretrained_models/halpe26_fast_res50_256x192.pth --video examples/video/cjs_exam.mp4 --outdir examples/results --save_video

* Webcam: Run AlphaPose using default webcam and visualize the results with:
python scripts/demo_inference.py --cfg <cfg_file> --checkpoint <trained_model> --outdir examples/res --vis --webcam 0

* Input list: Run AlphaPose for images in a list and save the rendered images with:
python scripts/demo_inference.py --cfg <cfg_file> --checkpoint <trained_model> --list examples/list-coco-demo.txt --indir <img_directory> --outdir examples/res --save_img

* Only-cpu/Multi-gpus: Run AlphaPose for images in a list by cpu only or multi gpus:
python scripts/demo_inference.py --cfg <cfg_file> --checkpoint <trained_model> --list examples/list-coco-demo.txt --indir <img_directory> --outdir examples/res --gpus ${-1(cpu only)/0,1,2,3(multi-gpus)}

* Re-ID Track(Experimental): Run AlphaPose for tracking persons in a video by human re-id algorithm:
python scripts/demo_inference.py --cfg <cfg_file> --checkpoint <trained_model> --video <path to video> --outdir examples/res --pose_track --save_video

* Simple Track(Experimental): Run AlphaPose for tracking persons in a video by MOT tracking algorithm:
python scripts/demo_inference.py --cfg <cfg_file> --checkpoint <trained_model> --video <path to video> --outdir examples/res --detector tracker --save_video

* Pose Flow(not ready): Run AlphaPose for tracking persons in a video by embedded PoseFlow algorithm:
python scripts/demo_inference.py --cfg <cfg_file> --checkpoint <trained_model. --video <path to video> --outdir examples/res --pose_flow --save_video

* Note: If you meet OOM(out of memory) problem, decreasing the pose estimation batch until the program can run on your computer:
python scripts/demo_inference.py --cfg <cfg_file> --checkpoint <trained_model> --indir <img_directory> --outdir examples/res --detbatch 1 --posebatch 30

* Getting more accurate: You can use larger input for pose network to improve performance e.g.:
python scripts/demo_inference.py --cfg <cfg_file> --checkpoint <trained_model> --indir <img_directory> --outdir <output_directory> --flip


### Motionbert command

* 3d pose
python infer_wild.py \
--vid_path examples/AlphaPose_cjs_exam.mp4 \
--json_path examples/alphapose-results.json \
--out_path examples/results

* mesh
python infer_wild_mesh.py \
--vid_path examples/AlphaPose_cjs_exam.mp4 \
--json_path examples/alphapose-results.json \
--out_path examples/results \
--ref_3d_motion_path examples/results/X3D.npy(option)

In [4]:
# 카메라 연결 확인 코드
import cv2

for i in range(5):
    cap = cv2.VideoCapture(i)
    if cap.isOpened():
        print(f"Webcam index {i} is available.")
        cap.release()
    else:
        print(f"Webcam index {i} is not available.")

Webcam index 0 is not available.
Webcam index 1 is not available.
Webcam index 2 is not available.
Webcam index 3 is not available.
Webcam index 4 is not available.


[ WARN:0@9418.283] global cap_v4l.cpp:997 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@9418.283] global obsensor_uvc_stream_channel.cpp:159 getStreamChannelGroup Camera index out of range
[ WARN:0@9418.286] global cap_v4l.cpp:997 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ERROR:0@9418.286] global obsensor_uvc_stream_channel.cpp:159 getStreamChannelGroup Camera index out of range
[ WARN:0@9418.288] global cap_v4l.cpp:997 open VIDEOIO(V4L2:/dev/video2): can't open camera by index
[ERROR:0@9418.288] global obsensor_uvc_stream_channel.cpp:159 getStreamChannelGroup Camera index out of range
[ WARN:0@9418.289] global cap_v4l.cpp:997 open VIDEOIO(V4L2:/dev/video3): can't open camera by index
[ERROR:0@9418.289] global obsensor_uvc_stream_channel.cpp:159 getStreamChannelGroup Camera index out of range
[ WARN:0@9418.291] global cap_v4l.cpp:997 open VIDEOIO(V4L2:/dev/video4): can't open camera by index
[ERROR:0@9418.291] global obsensor_uvc_stream_channel.c

In [7]:
# 3d pose 결과 numpy 파일 내용 확인 코드
import numpy as np

# npy 디렉토리
file_path = 'MotionBERT/examples/results/X3D.npy'

# npy 파일 읽기
data = np.load(file_path)

# 데이터 확인
print(data.shape) # (프레임 개수, 키포인트, (x,y,z) 좌표) 
print(data)

(629, 17, 3)
[[[-0.1434395   0.16969839  0.        ]
  [-0.25752604  0.18429506 -0.01000124]
  [-0.24302873  0.5482167   0.08387277]
  ...
  [-0.3006009  -0.34079653 -0.07275216]
  [-0.35476    -0.09653915  0.01704303]
  [-0.33017528  0.08956937 -0.13777421]]

 [[-0.14331692  0.17023128  0.00181606]
  [-0.25741172  0.18510553 -0.00931405]
  [-0.24157628  0.5480118   0.08331447]
  ...
  [-0.30294955 -0.33693945 -0.07028489]
  [-0.35721135 -0.09093743  0.02399519]
  [-0.33727947  0.09994338 -0.12779072]]

 [[-0.14296311  0.17066865  0.00175973]
  [-0.25721788  0.18584898 -0.00855563]
  [-0.24010554  0.54838955  0.08439484]
  ...
  [-0.3054209  -0.3323692  -0.06785031]
  [-0.3571838  -0.08278228  0.02912389]
  [-0.34230596  0.1137187  -0.11372767]]

 ...

 [[-0.151198    0.23738626  0.00505891]
  [-0.17300315  0.27391234 -0.10210109]
  [-0.14218947  0.6555146   0.1102583 ]
  ...
  [-0.23638639 -0.35786542 -0.19325882]
  [-0.2250172   0.01638646 -0.22114363]
  [-0.10014153  0.30553496 -0.2