In [2]:
import os
import random
import glob

from pathlib import Path
from PIL import Image
from torch.utils.data import Dataset
import torch

import pandas as pd
import numpy as np

import cv2

In [2]:
import requests
from bs4 import BeautifulSoup
import urllib

In [3]:
search_word = "벤치프레스"  # 검색어 설정
num_images = 50  # 가져올 이미지 수 설정

# Google 이미지 검색 결과 페이지 URL
url = f"https://www.google.com/search?tbm=isch&q={search_word}"

# requests를 사용하여 페이지에 접속
response = requests.get(url)

# BeautifulSoup을 사용하여 HTML 파싱
soup = BeautifulSoup(response.text, 'html.parser')

# 이미지 링크 추출
image_links = []
for img in soup.find_all('img'):
    if 'src' in img.attrs:
        image_links.append(img.attrs['src'])

print(len(image_links))
# 이미지 다운로드
for i, img_link in enumerate(image_links[:num_images]):
    try:
        # 이미지 다운로드 및 저장
        urllib.request.urlretrieve(img_link, f"{search_word}_{i}.jpg")
        print(f"Downloaded image {i+1}/{num_images}")
    except Exception as e:
        print(f"Error downloading image {i+1}: {e}")

print("Image download completed.")

21
Error downloading image 1: unknown url type: '/images/branding/searchlogo/1x/googlelogo_desk_heirloom_color_150x55dp.gif'
Downloaded image 2/50
Downloaded image 3/50
Downloaded image 4/50
Downloaded image 5/50
Downloaded image 6/50
Downloaded image 7/50
Downloaded image 8/50
Downloaded image 9/50
Downloaded image 10/50
Downloaded image 11/50
Downloaded image 12/50
Downloaded image 13/50
Downloaded image 14/50
Downloaded image 15/50
Downloaded image 16/50
Downloaded image 17/50
Downloaded image 18/50
Downloaded image 19/50
Downloaded image 20/50
Downloaded image 21/50
Image download completed.


In [5]:
import requests
from bs4 import BeautifulSoup
import urllib

def fetch_image_urls(search_term, num_images):
    url = f"https://www.google.com/search?tbm=isch&q={search_term}"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    img_tags = soup.find_all('img', limit=num_images)
    img_urls = [img['src'] for img in img_tags if img.get('src')]
    return img_urls

def download_images(img_urls, output_dir):
    for i, img_url in enumerate(img_urls):
        try:
            urllib.request.urlretrieve(img_url, f"{output_dir}/image_{i}.jpg")
            print(f"Downloaded image {i+1}/{len(img_urls)}")
        except Exception as e:
            print(f"Error downloading image {i+1}: {e}")

search_term = "your_search_term"
num_images = 30
output_dir = "images"

img_urls = fetch_image_urls(search_term, num_images)
download_images(img_urls, output_dir)

Error downloading image 1: unknown url type: '/images/branding/searchlogo/1x/googlelogo_desk_heirloom_color_150x55dp.gif'
Downloaded image 2/21
Downloaded image 3/21
Downloaded image 4/21
Downloaded image 5/21
Downloaded image 6/21
Downloaded image 7/21
Downloaded image 8/21
Downloaded image 9/21
Downloaded image 10/21
Downloaded image 11/21
Downloaded image 12/21
Downloaded image 13/21
Downloaded image 14/21
Downloaded image 15/21
Downloaded image 16/21
Downloaded image 17/21
Downloaded image 18/21
Downloaded image 19/21
Downloaded image 20/21
Downloaded image 21/21


In [11]:
data = glob.glob(os.path.join('.\images\*\*.jpg'))
image = cv2.imread('.\images\deadlift\\0.jpg')
print(image)
print(type(image))
print(len(data))
for index in range(len(data)):
    image_path = data[index]
    print(image_path)

    # 이미지를 읽어옴
    image = cv2.imread(image_path)
    print(image)
    print(type(image))

    # (224, 224)로 이미지 크기 조정
    width = 224
    height = 224
    resized_image = cv2.resize(image, (width, height), interpolation=cv2.INTER_LINEAR)

    # 조정한 이미지로 원본 이미지 덮어씌우기
    cv2.imwrite(image_path, resized_image)
    image = cv2.imread(image_path)

[[[255 255 255]
  [239 239 239]
  [255 255 255]
  ...
  [245 245 245]
  [255 255 255]
  [242 242 242]]

 [[252 252 252]
  [255 255 255]
  [255 255 255]
  ...
  [253 253 253]
  [255 255 255]
  [255 255 255]]

 [[248 248 248]
  [248 248 248]
  [255 255 255]
  ...
  [255 255 255]
  [251 251 251]
  [248 248 248]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
<class 'numpy.ndarray'>
500
.\images\benchpress\0.jpg
[[[ 49  49  49]
  [ 41  41  41]
  [ 36  36  36]
  ...
  [153 153 153]
  [166 166 166]
  [169 169 169]]

 [[ 61  61  61]
  [ 52  52  52]
  [ 46  46  46]
  ...
  [175 175 175]
  [187 187 187]
  [189 189 189]]

 [[ 64  64  64]
  [ 55  55  55]
  [ 47  47  47]
  ...
  [161 161 161]
  [171 171 171]
  [171 171 171]]

 ...